### create post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "sender": "Noam",
    "title": "This is my first Post",
    "content": "That's amazing"
}

### get all posts
GET http://localhost:3000/posts

### get all posts of user
GET http://localhost:3000/posts?sender=Noam

### get post by id
GET http://localhost:3000/posts/6757f7f435d05aac29575cec

### update post by id
PUT http://localhost:3000/posts/6757f7f435d05aac29575cec
Content-Type: application/json

{
    "content": "I love music"
}

### create comment
POST http://localhost:3000/comments
Content-Type: application/json

{
    "user": "Netanel",
    "content": "What a beautiful post!",
    "postId": "67546a2c774902f87260f238"
} 

### get all comments
GET http://localhost:3000/comments

###TO DO:
#  get comments by post id
# GET http://localhost:3000/comments/675493c7ae0f02cf47fee667

### update comment by id
PUT http://localhost:3000/comments/6757f8d1d1a268ddf083889c
Content-Type: application/json

{
    "content": "What an update!!!"
}

###delete comment by id
DELETE  http://localhost:3000/posts/60f3b4b3b3b3b3b3b3b3b3
